style:
  MagicNumber:
    active: false

naming:
  FunctionNaming:
    active: true
    ignoreAnnotated:
      - Composable
      - Preview

complexity:
  LongParameterList:
    constructorThreshold: 8
